// <copyright>
// Off The Record Messaging .NET, Copyright (c) 2013
//  based upon the original Off-the-Record Messaging library by
//    Ian Goldberg, Rob Smits, Chris Alexander,
//    Willy Lew, Lisa Du, Nikita Borisov
//    otr@cypherpunks.ca, http://www.cypherpunks.ca/otr/
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of version 2.1 of the GNU Lesser General
// Public License as published by the Free Software Foundation.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
// </copyright>
// <author>Bjorn Kuiper</author>
// <email>otr@kuiper.nu</email>

using System;
using System.Globalization;
using System.Numerics;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OffTheRecord.Tools;

namespace OffTheRecord.Tests.Tools
{
    [TestClass]
    public class EndianTests
    {
        #region Test methods

        [TestMethod]
        public void Endian_Validate_if_current_architecture_is_little_Endian()
        {
            if (Environment.OSVersion.Platform == PlatformID.Win32NT)
            {
                Endian.ArchitectureIsLittleEndian.Should().BeTrue("Running on Windows, this is expected to be Little Endian.");
                return;
            }

            if (Environment.OSVersion.Platform == PlatformID.Unix)
            {
                Endian.ArchitectureIsLittleEndian.Should().BeTrue("Running on Unix, this is expected to be Little Endian.");
                return;
            }

            Assert.Fail("Uknown platform: {0}", Environment.OSVersion.Platform);
        }

        [TestMethod]
        public void Endian_compare_results_from_BigEndian_architecture_with_current_architecture()
        {
            // Arrange
            const string expected = "415325779662433871844955547383752003988573073626";

            /* private key generated by libgcrypt, using different endian */
            const string x = "48BFDA215C31A9F0B226B3DB11F862450A0F30DA";

            // Act
            BigInteger actual = BigInteger.Parse(x, NumberStyles.HexNumber);

            // Assert
            actual.ToString().Should().Be(expected);
            actual.ToString("X").Should().Be(x);
        }

        [TestMethod]
        public void Endian_swaparray()
        {
            Endian.ConvertToBigEndianBytes(new byte[] {0x10}).Should().BeEquivalentTo(new byte[] {0x10});
            Endian.ConvertToBigEndianBytes(new byte[] {0x10, 0x11}).Should().BeEquivalentTo(new byte[] {0x11, 0x10});
            Endian.ConvertToBigEndianBytes(new byte[] {0x10, 0x11, 0x12}).Should().BeEquivalentTo(new byte[] {0x12, 0x11, 0x10});
            Endian.ConvertToBigEndianBytes(new byte[] {0x10, 0x11, 0x12, 0x13}).Should().BeEquivalentTo(new byte[] {0x13, 0x12, 0x11, 0x10});
        }

        #endregion
    }
}