//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffTheRecord.Tests.Toolkit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolkitResultResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolkitResultResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffTheRecord.Tests.Toolkit.ToolkitResultResource", typeof(ToolkitResultResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES key: 8863A4479AE2857FB9BE657E3B7E37C4
        ///MAC key: A43167D308BA9DE0127F3124A55BEA9A608C10C4
        ///.
        /// </summary>
        internal static string otr_mackey_exe {
            get {
                return ResourceManager.GetString("otr_mackey_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Message:
        ///	Version: 3
        ///	Flags: 0
        ///	Sender instance: 1261171266
        ///	Receiver instance: 4074827415
        ///	Sndr keyid: 1
        ///	Rcpt keyid: 1
        ///	DH y: 56857CF0BF9A28E53A5F6E408B17CF283BE28CA5151E119D4856654290395DEA73A3212A03C0136E360FC2313B15902957CEE8531F90428837F5B276180FF362AADA83FC6B4732D97C4F4ADC4ECF99469E5198A32C2400E614D87A6CD5FDCAEFF124222DB6AC0E634328D8BC5FF5D0B8648F8450F6FE3B65D773049646C35966224335F60A4E2586C1C6A7482C34B0613B09303C647399607ED65B51BDBF57AA14EE17A4BCDEA1B2F6233BA66DF24F4E3C6B0598E05386DB876E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string otr_parse_exe {
            get {
                return ResourceManager.GetString("otr_parse_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string otr_remac_exe {
            get {
                return ResourceManager.GetString("otr_remac_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are the high end of this key exchange.
        ///
        ///Our public key: 0B1BE99FD638D2B634F9825F753FF7F2213AE7207A390B5DF3B685A8516D63D49C3BCEEB826C1CD09EB030430772193B82F1F4AB01C77E38B7EFF100C0FB296BD1D6148BD205FDCE3A2EC33EF9C3413EB06D1F413D52AD0747B9273783F7EE88435498B5774967DA987CE10E7A2CEC72CEECC8F95CEAF92EDF82B3E0F69FAA87DE5EB4748325F82F0BC43F24984B5AF2C9D3043D9871C3C952B22A5B292CDEAD6A67CAA62C0196745ED608A6AAF8797FE5801F0506B8F8AA5F431DC583EA584A8
        ///
        ///Session id: 8FDEF45085A911525E8C408C5F9A3DB1C1104CB1
        ///
        ///Sendin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string otr_sesskeys_exe {
            get {
                return ResourceManager.GetString("otr_sesskeys_exe", resourceCulture);
            }
        }
    }
}
